- hosts: all
  tasks:
   - name: stop container
     shell: docker container stop mydockercontainer
   - name: remove container
     shell: docker container rm mydockercontainer
   - name: remove docker image
     shell: docker image rmi abhi9199/docker-job
   - name: create new container
     shell: docker container run -itd --name mydockercontainer -p 9000:80 abhi9199/docker-job
